apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
spec:
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: momentum49/messaging_app:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: messaging-app-db-config
              key: DATABASE_HOST

        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: messaging-app-db-config
              key: DATABASE_PORT

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: messaging-app-db-config
              key: MYSQL_DATABASE

        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: messaging-app-db-config
              key: DEBUG

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: messaging-app-db-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: messaging-app-db-secret
              key: MYSQL_PASSWORD

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: messaging-app-db-secret
              key: MYSQL_ROOT_PASSWORD

              
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: messaging-app-db-secret
              key: SECRET_KEY
