version: "3.9"
services:
  db:
    image: mysql
    container_name: web-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SECRET: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    depends_on:
      - db

volumes:
  db_data:

  




























